### PR TITLE
Make `::selection` more visible in dark mode

### PR DESCRIPTION
**Pull request by LeonardDrs**
### Before: 
Demo - basic one, only enabled dark theme
https://codesandbox.io/s/demo-docsify-themeable-forked-dd3g8?file=/index.html

image
image

### After:
Demo - added custom `<style>` in `index.html`
https://codesandbox.io/s/demo-docsify-themeable-forked-wyfyr

image
image

White mode:
image

### CODE REVIEW

**Comment by jhildenbiddle** [comment]
Hey @LeonardDrs.

Thanks for creating the PR.

Unfortunately, I don't think I will merge this PR for a few reasons:

1. Text selection should not alter the style of the text being selected. This PR inverts the color of the selected text (light when unselected, dark when selected).
1. The fix provided in this PR forces a non-configurable selected text color.
1. The text selection contrast issue is limited to Firefox (see below) and I don't want a fix for one browser to negatively impact other browsers.

I agree this text selection contrast issue should be addressed though. I'll dive in and see what I can come up with. 

For reference, here are some screenshots taken in Chrome, Safari, and Firefox. Notice that Chrome and Safari render a darker selection color (`#5e83af`) than the color specified in CSS (`#b4d5fe`). You can read more about why this happens and how to work around it [here](https://stackoverflow.com/questions/7224445/css3-selection-behaves-differently-in-ff-chrome).

**Chrome:** `#5e83af` (darker)

Screen Shot 2020-11-06 at 7 59 50 PM

**Safari:** `#5e83af` (darker)

Screen Shot 2020-11-06 at 8 00 00 PM


**Firefox:** `#b4d5fe` (actual)

Screen Shot 2020-11-06 at 8 06 43 PM

You can easily change the selection color consistently across browsers using the `--selection-color` property and an `rgba` value.

```html
<style>
    :root {
        --selection-color: rgba(94, 131, 175, 0.75);
    }
</style>
```

Here are screenshots of Chrome/Safari and Firefox with the above change:

**Chrome / Safari**

Screen Shot 2020-11-06 at 10 09 51 PM

**Firefox**

Screen Shot 2020-11-06 at 10 10 17 PM

**Comment by jhildenbiddle** [comment]
FYI, I have made a quick fix for the text selection in 0.8.4: https://github.com/jhildenbiddle/docsify-themeable/commit/6b904bc7fdb9313c466deaa24b633e207ef64f25

**Comment by LeonardDrs** [comment]
Nice!

Thanks a lot.

Quick questions:
> Text selection should not alter the style of the text being selected

Didn't knew, thanks. Where does that come from? a11y?

> The fix provided in this PR forces a non-configurable selected text color.

Should have I created a css variable for that? (even though it was the wrong fix)

Sorry, didn't took time to look for all browser at the time, nice catch.

**Comment by jhildenbiddle** [comment]
>> Text selection should not alter the style of the text being selected

> Where does that come from? a11y?

I can't say for certain that this is a hard rule or even an accessibility recommendation, but you'll notice that this is the pattern in browsers and operating systems in general. Perhaps I should have said "I prefer" instead of just "should not". :)

>> The fix provided in this PR forces a non-configurable selected text color.

> Should have I created a css variable for that? (even though it was the wrong fix)

Not necessarily. My concern was really related more to the first issue (the fact that text color changing on selection) than the fact that the text selection color wasn't configurable. In other words: "you're changing the text color on selection *and* making it harder for users to change back".

Anyway, I do appreciate the PR and calling attention to the issue. So thanks!

**Comment by LeonardDrs** [comment]
My thanks to you, was nice to chat with you.

**Pull request closed without merging**
